"""link_user_and_cart_relationships

Revision ID: 45edb4502f2d
Revises: ef72e6f9becf
Create Date: 2026-03-12 00:39:22.625717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45edb4502f2d'
down_revision: Union[str, Sequence[str], None] = 'ef72e6f9becf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
