"""add_is_active_and_created_at

Revision ID: be10d3929c44
Revises: 3e43e6ebc1ff
Create Date: 2026-03-03 11:13:17.832826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be10d3929c44'
down_revision: Union[str, Sequence[str], None] = '3e43e6ebc1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add is_active with a default of True for existing rows
    op.add_column('users', sa.Column(
        'is_active', 
        sa.Boolean(), 
        nullable=False, 
        server_default=sa.text('true')
    ))
    
    # 2. Add created_at with the current timestamp for existing rows
    op.add_column('users', sa.Column(
        'created_at', 
        sa.DateTime(), 
        nullable=False, 
        server_default=sa.func.now()
    ))
    
    # Optional: Remove server_defaults so your Python model handles defaults from now on
    op.alter_column('users', 'is_active', server_default=None)
    op.alter_column('users', 'created_at', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
