"""add total_price to orders

Revision ID: ef72e6f9becf
Revises: 93b44de1b574
Create Date: 2026-03-11 14:49:37.298815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef72e6f9becf'
down_revision: Union[str, Sequence[str], None] = '93b44de1b574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###
